language: python
python:
  - "2.7"
script: nosetests xivo_confd
notifications:
  email:
    recipients:
      - tests-reports@avencall.com
    on_success: change
    on_failure: change
branches:
  only:
    - master